"""LLM safety layer — filter harmful output, inject disclaimers, restrict dosage."""

MEDICAL_DISCLAIMER = (
    "⚠️ DISCLAIMER: This analysis is generated by an AI system and is NOT a substitute "
    "for professional medical advice, diagnosis, or treatment. Always seek the advice of "
    "a qualified healthcare provider with any questions you may have regarding a medical condition."
)

DOSAGE_WARNING = (
    "⚠️ Specific dosage information has been withheld for safety. "
    "Please consult a healthcare professional for proper dosage and medication guidance."
)

# Keywords that suggest harmful or inappropriate content
_HARMFUL_KEYWORDS = [
    "suicide", "self-harm", "kill yourself", "overdose instruction",
]

# Dosage-related patterns to flag
_DOSAGE_PATTERNS = [
    "mg twice daily", "mg once daily", "ml per day", "tablets per day",
    "take 2 pills", "take 3 pills", "dosage:", "dose:",
]


def filter_harmful_output(text: str) -> str:
    """Remove or flag harmful content from LLM output."""
    lower = text.lower()
    for keyword in _HARMFUL_KEYWORDS:
        if keyword in lower:
            return (
                "The AI system detected potentially harmful content and has blocked this response. "
                "Please consult a healthcare professional directly."
            )
    return text


def inject_disclaimer(text: str) -> str:
    """Append medical disclaimer to treatment-related responses."""
    return f"{text}\n\n{MEDICAL_DISCLAIMER}"


def flag_dosage_suggestions(text: str) -> str:
    """Add safety warnings around specific dosage mentions."""
    lower = text.lower()
    has_dosage = any(pattern in lower for pattern in _DOSAGE_PATTERNS)
    if has_dosage:
        return f"{text}\n\n{DOSAGE_WARNING}"
    return text


def apply_safety(text: str, is_treatment: bool = False) -> str:
    """Apply all safety filters to LLM output."""
    text = filter_harmful_output(text)
    text = flag_dosage_suggestions(text)
    if is_treatment:
        text = inject_disclaimer(text)
    return text
